services:
  - type: web
    name: footymetrics-backend
    env: docker
    rootDir: backend
    dockerfilePath: Dockerfile
    plan: free
    healthCheckPath: /leaderboard
    envVars:
      - key: PORT
        value: 8080
      - key: BREVO_SMTP_USER
        sync: false
      - key: BREVO_SMTP_KEY
        sync: false
